header:
  version: 8

machine: raspberrypi2
distro: poky
target:
  - core-image-base

repos:

  meta-cord:
    path: layers/meta-cord

  poky:
    url: https://git.yoctoproject.org/git/poky
    path: layers/third-party/poky
    refspec: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/third-party/meta-openembedded
    refspec: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-perl:

  meta-qt5:
    url: https://github.com/meta-qt5/meta-qt5/
    path: layers/third-party/meta-qt5
    refspec: scarthgap

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi
    path: layers/third-party/meta-raspberrypi
    branch: scarthgap

bblayers_conf_header:
  standard: |
    # YOCTOROOT will be updated with the correct path once build-env is sourced
    YOCTOROOT = "${TOPDIR}/../layers"
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""
local_conf_header:
  dl_paths: |
    OPTDIR = "/opt/cord"
    # Where to place downloaded files
    DL_DIR ?= "${OPTDIR}/yocto/downloads"
    # Where to place shared-state files
    SSTATE_DIR ?= "${OPTDIR}/yocto/sstate-cache"
    # # Where to place the build output
    # TMPDIR = "${OPTDIR}/yocto/tmp"
  # reduce_diskspace: |
  #   INHERIT += "rm_work_and_downloads"
  standard: |
    CONF_VERSION = "2"
    # PACKAGE_CLASSES = "package_rpm"
    SDKMACHINE = "x86_64"
    USER_CLASSES = "buildstats"
    PATCHRESOLVE = "noop"
  debug-tweaks: |
    EXTRA_IMAGE_FEATURES = "debug-tweaks"
  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
